# Calra Sim Config Parameters
carla:
  server: '192.168.1.211'
  port: 2000
  autopilot: False
  timeout: 200
  no_rendering_mode: True
  world: 'Town04'
  vehicle_tag: 'european_hgv'
  #vehicle_tag: 'charger_2020'
  #vehicle_tag: 'wrangler_rubicon'
  steering_dead_zone: 0.1   # 0.001 for fanatec
  fps: 10

recorder:
  save_debug_images: False
  task_name: '20250723_014'
  driving_lanes_only: True

sim:
  sim_seconds: 300
  real_time_mode: True
  default_control: 'Logitech G920 Driving Force Racing Wheel' #'G920_Racing_Wheel'
  windows:
    front_res: [2560,1440]
    mirror_res: [640,480]
    dashcam_res: [550,350]

  # Note: different vehicles have different mirror locations, add new locations below
  mirror_location:
    european_hgv:
      left: [2, -1, 2]
      right: [2, 1, 2]
    charger_2020:
      left: [0.5, -1, 1.0]
      right:  [0.5, 1, 1.0]
    wrangler_rubicon:
      left: [0.5, -1, 1.5]
      right:  [0.5, 1, 1.5]   

  controls:
    PXN V900:
      steering_wheel: 0
      throttle: 5               
      brake: 2
      reverse: 0
      handbrake: 4
      accel: 3
    Logitech G920 Driving Force Racing Wheel:
      steering_wheel: 0
      throttle: 1               
      brake: 3
      reverse: 15
      handbrake: 4
      accel: 14
    xboxone:
      steering_wheel: 0
      throttle: 5
      brake: 2
      reverse: 0
      handbrake: 1
      accel: 4
    fanatec:
      steering_wheel: 0
      throttle: 1
      brake: 4
      reverse: 1
      handbrake: 2 
